name: Move Changed Files

on:
  push:
    branches:
      - main  # oder den Namen Ihrer Hauptentwicklungsbranch

jobs:
  move_changed_files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Check for changes
        id: check_changes
        run: |
          previous_commit=${GITHUB_SHA}^
          changed_files=$(git diff --name-status $previous_commit HEAD)
          if [ -z "$changed_files" ]; then
            echo "No changes detected."
            exit 1
          fi
          echo "::set-output name=changed_files::$changed_files"
          
      - name: Move changed files
        run: |
          mkdir -p data_extern/
          while IFS= read -r line; do
            status=$(echo "$line" | cut -d' ' -f1)
            file=$(echo "$line" | cut -d' ' -f2-)
            if [ "$status" != "D" ]; then
              cp -t data_extern/ "$file"
            fi
          done <<<"${{ steps.check_changes.outputs.changed_files }}"
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config --global url.https://${{ secrets.first }}@github.com/.insteadOf https://github.com/
          git add .
          git commit -m "Move changed files from source to destination"
          git push
