name: Copy Modified File

on:
  push:
    branches:
      - main 
    paths:
      - 'data/*.md'

jobs:
  copy_modified_file:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Check for changed files
        id: check_changes
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          if [ -z "$changed_files" ]; then
            echo "No changes detected."
            exit 0
          fi
          echo "::set-output name=changed_files::$changed_files"
          
      - name: Copy modified file
        run: |
          mkdir -p data_extern
          for file in ${{ steps.check_changes.outputs.changed_files }}; do
            cp "$file" data_extern/
          done
