name: Move Changed Files

on:
  push:
    branches:
      - main  # oder den Namen Ihrer Hauptentwicklungsbranch

jobs:
  move_changed_files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Get previous commit hash
        id: get_previous_commit
        run: |
          previous_commit=$(git log --pretty=format:'%h' -n 1)
          echo "::set-output name=previous_commit::$previous_commit"
          
      - name: Check for changes
        id: check_changes
        run: |
          changed_files=$(git diff --name-only ${{ steps.get_previous_commit.outputs.previous_commit }} HEAD)
          if [ -z "$changed_files" ]; then
            echo "No changes detected."
            exit 1
          fi
          echo "::set-output name=changed_files::$changed_files"
          
      - name: Move changed files
        run: |
          mkdir -p data_extern/
          cp -t data_extern/ ${{ steps.check_changes.outputs.changed_files }}
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config --global url.https://${{ secrets.first }}@github.com/.insteadOf https://github.com/
          git add .
          git commit -m "Move changed files from source to destination"
          git push
