name: Push Changed File

on:
  push:
    paths:
      - 'data/**'  # Pfade anpassen
  pull_request:
    paths:
      - 'data/**'  # Pfade anpassen

jobs:
  push-changed-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get changed file
        id: get_changed_file
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- 'path/to/source/' > changed_files.txt
          cat changed_files.txt

      - name: Copy changed file
        run: |
          changed_file=$(cat changed_files.txt)
          if [ -n "$changed_file" ]; then
            mkdir -p data_extern
            cp "$changed_file" data_extern
          else
            echo "No files changed."
            exit 0
          fi

      - name: Commit and push changed file
        run: |
          cd data_extern
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config --global url.https://${{ secrets.first }}@github.com/.insteadOf https://github.com/
          git add .
          git commit -m "Update changed file"
          git push
