name: Delete files and create empty folder

on:
 repository_dispatch:
    types: [push]

jobs:
  push-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone target repository
        run: git clone https://github.com/matze240/second_repo.git second_repo
        # Replace 'yourusername' with your GitHub username and 'target-repo' with the name of your target repository

     
      - name: Copy folder to target repository
        run: |
          cp -r data_extern/* second_repo/data_new
          cd second_repo
          git config --local user.email "action@github.com"
          git config --local user.name "matze2402"
          git config --global url.https://${{ secrets.first}}@github.com/.insteadOf https://github.com/
          git add .
          git commit -m "Copy files from source repository"
          git push

      - name: Dispatch trigger for delete
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.first }}
          repository: Matze240/fremd_repo
          event-type: delete 
